version: '3.5'

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - ${TYPEORM_PORT}:5432

volumes:
    postgres: